management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable discovery service integration
          lower-case-service-id: true # Match service IDs with lowercase (Eureka might uppercase)
      routes:
        - id: user-service-route
          uri: lb://xpenser-user-service # 'lb://' means load-balanced, followed by Eureka service ID
          predicates:
            - Path=/api/user/** # Requests starting with /api/user will be routed
          filters:
            - StripPrefix=1 # Removes '/api' from the path before forwarding
            # Example: /api/user/details/user -> /user/details/user on user-service
            # This filter is crucial to map the gateway path to the actual microservice path.
            - TokenRelay=true # gateway should also forward the user's token (not needed for Auth Server calling it)