management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true # Enable discovery service integration
          lower-case-service-id: true # Match service IDs with lowercase (Eureka might uppercase)
      routes:
        - id: user-service-route
          uri: lb://xpenser-user-service # 'lb://' means load-balanced, followed by Eureka service ID
          predicates:
            - Path=/api/user/** # Requests starting with /api/user will be routed
          filters:
            - StripPrefix=2 # Removes '/api/user' from the path before forwarding
            # Example: /api/user/details/user -> /user/details/user on user-service
            # This filter is crucial to map the gateway path to the actual microservice path.
            # - TokenRelay=true # gateway should also forward the user's token (not needed for Auth Server calling it)
        
        - id: expense-service-route
          uri: lb://xpenser-expense-service
          predicates:
            - Path=/api/expense/**
          filters:
            - StripPrefix=2
            
        - id: document-service-route
          uri: lb://xpenser-document-service 
          predicates:
            - Path=/api/document/** 
          filters:
            - StripPrefix=2 
            

