
gateway:
  services:
    user-service: 
      name: xpenser-user-service
      path-prefix: /api/user

# Custom properties for Authorization Server configuration
auth-server:
  issuer-uri: http://${eureka.instance.hostname}:${server.port}
  endpoints:
    authorization: /oauth2/authorize
    pushed-authorization-request: /oauth2/par
    device-authorization: /oauth2/device_authorization
    device-verification: /oauth2/device_verification
    token: /oauth2/token
    token-introspection: /oauth2/introspect
    token-revocation: /oauth2/revoke
    jwk-set: /oauth2/jwks
    oidc-logout: /connect/logout
    oidc-user-info: /userinfo
    oidc-client-registration: /connect/register



    

