management:
  endpoints:
    web:
      exposure:
        include: "*" 

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SERVER_NAME:neverland}?currentSchema=${DB_SCHEMA:xpenser_user_service}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  r2dbc: # Reactive database connection for WebFlux
    url: ${R2DBC_URL:r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_SERVER_NAME:neverland}?currentSchema=${DB_SCHEMA:xpenser_user_service}}
    username: ${DB_USER:peterpan}
    password: ${DB_PASSWORD:P3terP@n}
    # No driver-class-name needed for R2DBC
    pool: # Connection pool for R2DBC (e.g., r2dbc-pool)
      max-size: 10
      initial-size: 5
      max-idle-time: 30m
      validation-query: SELECT 1
      # Other pool properties as needed

  flyway: # Flyway still manages schema, even for R2DBC
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # This is crucial for your resource server.
          # Replace with the issuer URI of your Authorization Server (e.g., Keycloak, Auth0, Okta).
          # The resource server will use this to retrieve the public keys to validate JWTs.
          issuer-uri: http://localhost:9000/realms/master # Example: your Auth Server's issuer URI
          # If using an opaque token (introspection), you'd use:
          # opaquetoken:
          #   introspection-uri: http://localhost:9000/oauth2/introspect
          #   client-id: user-service-client
          #   client-secret: secret