management:
  endpoints:
    web:
      exposure:
        include: "*" 

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SERVER_NAME:neverland}?currentSchema=${DB_SCHEMA:xpenser_user_service}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  r2dbc: # Reactive database connection for WebFlux
    url: ${JDBC_URL:jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SERVER_NAME:neverland}?currentSchema=${DB_SCHEMA:xpenser_user_service}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          # This is crucial for your resource server.
          # Replace with the issuer URI of your Authorization Server (e.g., Keycloak, Auth0, Okta).
          # The resource server will use this to retrieve the public keys to validate JWTs.
          issuer-uri: http://localhost:9000/realms/master # Example: your Auth Server's issuer URI
          # If using an opaque token (introspection), you'd use:
          # opaquetoken:
          #   introspection-uri: http://localhost:9000/oauth2/introspect
          #   client-id: user-service-client
          #   client-secret: secret